# Generated by Django 4.1.2 on 2024-07-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
