# Generated by Django 4.1.2 on 2024-07-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_delete_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='idlibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('descripcion_l', models.CharField(max_length=255)),
            ],
        ),
    ]
